global:
  scrape_interval: 5s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  # Scrape vLLM /metrics on the other machine
  - job_name: "vllm"
    metrics_path: /metrics
    scheme: http           # use https if your endpoint is TLS
    static_configs:
      - targets:
          - "127.0.0.1:3000"
          - "127.0.0.1:3001"
          - "127.0.0.1:3002"
          - "127.0.0.1:3003"
          - "127.0.0.1:3004"
          - "127.0.0.1:3005"
          - "127.0.0.1:3006"
          - "127.0.0.1:3007"
          - "127.0.0.1:3008"
          - "127.0.0.1:3009"
          - "127.0.0.1:7113"
          - "127.0.0.1:7114"
          - "127.0.0.1:7115"
          - "127.0.0.1:7116"
          - "127.0.0.1:7117"
          - "127.0.0.1:7118"


    # If your /metrics is protected, uncomment and fill:
    # basic_auth:
    #   username: YOUR_USER
    #   password: YOUR_PASS
    # bearer_token: /etc/prometheus/token
    # tls_config:
    #   insecure_skip_verify: true   # only for self-signed certs (dev)

  # Scrape Prometheus itself (useful for sanity checks)
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
